api_platform:
  defaults:
    pagination_enabled: true
    pagination_client_partial: true # Disabled by default
  collection:
    pagination:
      page_parameter_name: _page
      partial_parameter_name: 'partial' # Default value