api_platform:
  # Set this to false if you want Webby to disappear.
  show_webby: false
  mapping:
    paths:
#      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/ApiResource'
#      - '%kernel.project_dir%/config/api_platform/resources'
  defaults:
    pagination_enabled: true
    pagination_client_partial: true # Disabled by default
    pagination_items_per_page: 10
    pagination_client_items_per_page: true
  collection:
    pagination:
      page_parameter_name: _page
      partial_parameter_name: 'partial' # Default value
      items_per_page_parameter_name: itemsPerPage

  exception_to_status:
    App\Response\Rabbit\RabbitBadRequest: 400