api_platform:
  defaults:
    pagination_enabled: true
    pagination_client_partial: true # Disabled by default
    pagination_items_per_page: 10
    pagination_client_items_per_page: true
  collection:
    pagination:
      page_parameter_name: _page
      partial_parameter_name: 'partial' # Default value
      items_per_page_parameter_name: itemsPerPage