networks:
  default:
    external: true
    name: gateway

services:
  nginx:
    labels:
      traefik.enable: "true"
      traefik.http.services.ace_nginx-80.loadbalancer.server.port: "80"
      traefik.http.routers.ace_nginx.entrypoints: "web"
      traefik.http.routers.ace_nginx.rule: "Host(`ace-old.localhost`)"
    container_name: ace_nginx
    hostname: ace_nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    depends_on:
      - php

    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
    networks:
      - default
#      - dev0
  php:
    container_name: ace_php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www
      - ./images/php/:/usr/local/etc/php/custom.d
    environment:
      - PHP_IDE_CONFIG=serverName=ace
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d
    depends_on:
      - postgresql
    networks:
      - default
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: ace_postgres
    environment:
      - POSTGRESQL_USERNAME=ace
      - POSTGRESQL_PASSWORD=ace
      - POSTGRESQL_DATABASE=ace_db
    ports:
      - 5530:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default
#      - dev0