api_platform:
    resource: .
    type: api_platform
    prefix: /api

rabbit:
    path: /rabbit
    controller: App\Controller\RandomRabbit::rabbit

cat:
    path: /cat
    controller: App\Controller\RandomRabbit::cat