api_platform:
    resource: .
    type: api_platform
    prefix: /api

rabbit:
    path: /api/rabbit
    controller: App\Controller\RandomRabbit::rabbit

cat:
    path: /api/cat
    controller: App\Controller\RandomRabbit::cat
    prefix: /api