jwt_auth:
  path: /api/login
  methods: ['POST']

app_login:
  path: /login
  controller: App\Controller\AuthController::login
  methods: ['GET','POST']

app_logout:
  path: /logout
  controller: App\Controller\AuthController::logout
  methods: ['GET','POST']