# This file is inside /config/api_platform/resources/user.yaml
resources:
  App\ApiResource\Cat:
    shortName: Kitties
    operations:
      ApiPlatform\Metadata\Get:
#        controller: App\Controller\CatController::cat
        uriTemplate: '/api/cat'
        routeName: 'cat_get'
        name: 'cat_get'
        access_control: is_granted('VIEW', object)

      ApiPlatform\Metadata\Patch:
        uriTemplate: '/api/cat'
        routeName: 'cat_patch'
        name: 'cat_patch'
        access_control: is_granted('VIEW', object)