resources:
  App\Entity\Test:
    shortName: TestObject
    description: TestDescription
    collectionOperations:
      summary:
      get:
        method: 'GET'
        path: '/get_dummy'
        controller: 'App\Controller\TestLoadController'
        openapi_context:
          tags: [ 'TestObj' ]
          summary: 'Test some'
          description: 'Descr test'
          responses:
            201:
              description: 'Created'
              content:
                application/json:
                  schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: 'ok'
                    token:
                      type: string
                    refresh_token:
                      type: string
            400:
              description: 'Invalid input'
            422:
              description: 'Email already in use'
    attributes:
      order:
        referenceCafHuissier: asc
        montantEcheance: asc

      # security: 'is_granted("ROLE_USER")'
      normalization_context:
        groups: [ 'myentity:read' ]
      denormalization_context:
        groups: [ 'myentity:write' ]
    properties:


    exportcsv:
      security: 'is_granted("ROLE_MYENTITY_ADMIN")'
      # pagination_partial: true
      method: 'GET'
      path: '/myentity/export'
      controller: 'App\Controller\MyEntityController::export'
      openapi_context:
        summary: Export CSV
        parameters: [ ]
        responses:
          '200':
            description: Génération réussi de l'export CSV
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    type:
                      type: string
                      description: mime-type du fichier.
                    content:
                      type: string
                      description: Base64 du contenu du fichier.