# This file is inside /config/api_platform/resources/user.yaml
resources:
  App\Entity\User:
    shortName: UserNames
    description: UserDescription
#    operations:
#      Get:
#        method: 'GET'
#        access_control: is_granted('VIEW', object)